### ISSUE TITLE
Increasing the bandwidth of the probe

### ISSUE THREAD

**Issue by apoorav-singh** [Strathclyde-EQOP/nV-Hunter-voltage-probe#5]
Hi,

Can the probe's bandwidth be increased? If yes, which resistor capacitors should change?
Was it tested with other bandwidths?

Thanks.

**Comment by mmroz39** [comment]
Hello,

The bandwidth of the probe can be adjusted. Our application used a fixed bandwidth, so it was not tested.
You would need to change the compensation capacitors at ADA4523s and re-design the Sallen-Key filter to adjust the bandwidth. Depending on how much increase in bandwidth you would want, you might need to also lower the gain of the ADA4523s.
